version: '3.3'
services:
  db:
    container_name: mysql-db
    domainname: mysql-db
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'contest-manager'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_ROOT_HOST: '172.19.0.1'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysqldata:/var/lib/mysql:rw,delegated
